version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"  # Exposing the port to local machine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_transport
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ AMQP port
    networks:
      - mynetwork

# Define the network 'mynetwork' here
networks:
  mynetwork:
    driver: bridge  # Use the bridge network driver, which is the default

volumes:
  postgres-data:
