export const USERPATTERN = {
    FINDALLUSERS: 'users.findAll',
    FINDMANYBYUNIQUEIDENTIFIER: 'users.FINDMANYBYUNIQUEIDENTIFIER',
    FINDBYID: 'users.findOneById',
    CREATEUSER: 'users.create',
    LOGINUSER: 'users.login',
    VERIFYUSER: 'users.verify',
    RESENDUSER: 'users.resend',
    BOOKMARK: 'users.bookmark',
    UPDATE: 'users.update',
    DELETE: 'users.delete',
    RESETPASSWORD: 'users.resetPassword',
    CHANGEPASSWORD: 'users.changePassword',
    LOGOUT: 'users.logout',
}